project:
  type: website
  output-dir: docs

website:
  title: "Biomaths & Julia"
  sidebar:
    style: floating
    contents:
      - index.qmd
      - pop_isolees.qmd
      - pop_exploitees.qmd
      - pop_interactions.qmd
      - pop_interactions2.qmd
      - annexes.qmd
      - about.qmd
  page-footer: "Copyright 2023, Ludovic Mailleret"
  repo-url: https://github.com/lmaillere/biomaths_www
  repo-actions: [edit, issue]

highlight-style: pygments

reference-location: margin

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true
    html-math-method: katex

license: CC BY-NC

bibliography: references.bib

jupyter: julia-1.10

execute:
 cache: true
 output: false
 freeze: false  # re-render only when source changes
